version: "1.0"

services:
  web:
    image: vatsalshah01/bitnet-inference:latest
    expose:
      - port: 8000
        as: 8000
        to:
          - global: true

profiles:
  name: bitnet-llama3-8b
  duration: 30min
  tier:
    - community
  mode: provider
  compute:
    web:
      resources:
        cpu:
          units: 8
        memory:
          size: 24Gi
        storage:
          size: 100Gi
        gpu: #optional
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090
  placement:
    westcoast:
      attributes:
        region: us-west
      pricing:
        web:
          token: USDT
          amount: 1

deployment:
  web:
    westcoast:
      profile: web
      count: 1
