version: "1.0"

services:
  web:
    image: ghcr.io/flock-io/llm-loss-validator:latest
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
    env:
      - FLOCK_API_KEY=
      - TASK_ID=
      - HF_TOKEN=

profiles:
  name: flock
  duration: 30min
  tier:
    - community
  compute:
    web:
      resources:
        cpu:
          units: 8
        memory:
          size: 24Gi
        storage:
          size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090
  placement:
    westcoast:
      attributes:
        region: us-west
      pricing:
        web:
          token: USDT
          amount: 1

deployment:
  web:
    westcoast:
      profile: web
      count: 1
