version: "1.0"
 
services:
  web:
    image: linuxserver/steamos
    user: root
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 3001
        as: 3001
        to:
          - global: true
      - port: 6901
        as: 6901
        to:
          - global: true
      - port: 5901
        as: 5901
        to:
          - global: true
      - port: 4901
        as: 4901
        to:
          - global: true
      - port: 8080
        as: 8080
        to:
          - global: true
    env:
      - TEST=test
      - VNC_PW=password
profiles:
  name: kali-linux
  duration: 6h
  mode: fizz # or 'fizz' for Fizz Mode
  tier:
    - community
  compute:
    web:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          size: 100Gi
  placement:
    westcoast:
      pricing:
        web:
          token: CST
          amount: 0.1
  gpu:
    units: 1
    attributes:
      vendor:
        nvidia:
          - model: gtx1080
deployment:
  web:
    westcoast:
      profile: web
      count: 1
