version: "1.0"

services:
  unsloth-finetuning:
    image: spheronnetwork/unsloth-finetuning:cuda12-pytorch
    pull_policy: IfNotPresent
    expose:
      - port: 8888
        as: 8888
        to:
          - global: true
    env:
      - JUPYTER_TOKEN=testing123
profiles:
  name: unsloth-finetuning
  duration: 1h
  tier:
    - community
  compute:
    unsloth-finetuning:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          - size: 200Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090
  placement:
    westcoast:
      attributes:
        region: us-west
      pricing:
        unsloth-finetuning:
          token: USDT
          amount: 5

deployment:
  unsloth-finetuning:
    westcoast:
      profile: unsloth-finetuning
      count: 1
